apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongos
spec:
  selector:
    app: mongos
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: LoadBalancer
