apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongos
spec:
  selector:
    matchLabels:
      app: mongos
  serviceName: mongo
  replicas: 2
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:latest
          command: ["mongod", "--replSet", "rs0", "--config", "/etc/mongod.conf"]
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: 512Mi
              cpu: 32m
            requests:
              memory: 512Mi
              cpu: 32m
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-config
              mountPath: /etc/mongod.conf
              subPath: mongodb.conf
            - name: mongodb-log
              mountPath: /var/log/mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
      volumes:
        - name: mongo-config
          configMap:
            name: mongo-config
        - name: mongodb-log
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard-csi
        resources:
          requests:
            storage: 1Gi
